
    const nameEl = document.getElementById('name');
    const macEl = document.getElementById('mac');
    const datetimeEl = document.getElementById('datetime');
    const extEl = document.getElementById('ext');
    const passwordEl = document.getElementById('password');
    const previewEl = document.getElementById('preview');
    const statusEl = document.getElementById('status');
    const excelFileEl = document.getElementById('excelFile');
    const excelPasswordPrefixEl = document.getElementById('excelPasswordPrefix');
    const downloadExcelBtn = document.getElementById('downloadExcelBtn');
    const excelPreviewEl = document.getElementById('excelPreview');
    const excelStatusEl = document.getElementById('excelStatus');
    const tabs = Array.from(document.querySelectorAll('.tab'));
    const panels = Array.from(document.querySelectorAll('.tab-panel'));
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';

    let excelRows = [];

    function generatePassword(length = 20) {
      const values = new Uint32Array(length);
      crypto.getRandomValues(values);
      let out = '';
      for (let i = 0; i < length; i++) {
        out += chars[values[i] % chars.length];
      }
      return out;
    }

    function formatDateTime(value) {
      if (!value) return '';
      const d = new Date(value);
      if (Number.isNaN(d.getTime())) return value;
      return d.toLocaleString('en-US', {
        year: 'numeric',
        month: 'numeric',
        day: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
        second: '2-digit'
      });
    }

    function buildText() {
      const name = nameEl.value.trim();
      const dt = formatDateTime(datetimeEl.value);
      const ext = extEl.value.trim();
      const password = passwordEl.value.trim() || generatePassword(20);

      return [
        `## AUTOGENERATED by ${name} Avaya Auto Login Enabler at ${dt}`,
        `SET FORCE_SIP_USERNAME "${ext}"`,
        `SET FORCE_SIP_PASSWORD "${password}"`
      ].join('\n');
    }

    function buildTextFromRow(row) {
      const name = nameEl.value.trim() || 'Hosam';
      const dt = formatDateTime(datetimeEl.value) || formatDateTime(new Date().toISOString());
      const ext = row.ext.trim();
      const password = getPasswordForRow(row);

      return [
        `## AUTOGENERATED by ${name} Avaya Auto Login Enabler at ${dt}`,
        `SET FORCE_SIP_USERNAME "${ext}"`,
        `SET FORCE_SIP_PASSWORD "${password}"`
      ].join('\n');
    }

    function setStatus(message, type = '') {
      statusEl.textContent = message;
      statusEl.className = `status ${type}`.trim();
    }

    function setExcelStatus(message, type = '') {
      excelStatusEl.textContent = message;
      excelStatusEl.className = `status ${type}`.trim();
    }

    function updatePreview() {
      previewEl.textContent = buildText();
    }

    function validateFields() {
      const missing = [];
      if (!nameEl.value.trim()) missing.push('Name');
      if (!macEl.value.trim()) missing.push('MAC Address');
      if (!datetimeEl.value.trim()) missing.push('Date & Time');
      if (!extEl.value.trim()) missing.push('Ext Number');
      return missing;
    }

    function safeFilenameFromMac(macValue = '') {
      const mac = (macValue || macEl.value.trim()).replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
      return `${mac || 'intake'}_physical.txt`;
    }

    function downloadTextContent(text, filename) {
      const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    }

    function downloadTxt() {
      const missing = validateFields();
      if (missing.length) {
        setStatus(`Please fill in: ${missing.join(', ')}`, 'error');
        return;
      }

      if (!passwordEl.value.trim()) passwordEl.value = generatePassword(20);

      downloadTextContent(buildText(), safeFilenameFromMac());
      setStatus(`Downloaded ${safeFilenameFromMac()}`, 'ok');
      updatePreview();
    }

    function normalizeHeader(value) {
      return String(value || '').trim().toLowerCase().replace(/[^a-z0-9]/g, '');
    }

    function getValue(row, keys) {
      for (const key of keys) {
        const normalizedKey = normalizeHeader(key);
        const rawValue = row[normalizedKey];
        if (rawValue !== undefined && rawValue !== null && String(rawValue).trim() !== '') {
          return String(rawValue).trim();
        }
      }
      return '';
    }

    function normalizeLoginValue(value) {
      const cleaned = String(value || '').trim().split('@')[0];
      return cleaned.replace(/[^a-zA-Z0-9]/g, '');
    }

    function normalizeMacValue(value) {
      return String(value || '').trim().replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
    }

    function normalizeRow(row) {
      const normalized = {};
      Object.entries(row).forEach(([key, value]) => {
        normalized[normalizeHeader(key)] = value ?? '';
      });

      const loginValue = normalizeLoginValue(getValue(normalized, ['login']));
      const extValue = loginValue || getValue(normalized, ['extention', 'extension', 'ext', 'extnumber']);

      return {
        ext: extValue,
        login: loginValue,
        mac: normalizeMacValue(getValue(normalized, ['devicemac', 'macaddress', 'mac'])),
      };
    }

    function getPasswordForRow(row) {
      const passwordPrefix = (excelPasswordPrefixEl.value || '').trim();
      return `${passwordPrefix}${row.login || ''}`.trim();
    }

    function renderExcelPreview() {
      if (!excelRows.length) {
        excelPreviewEl.textContent = 'Imported Excel rows will appear here.';
        return;
      }

      excelPreviewEl.textContent = excelRows
        .map((row, index) => `Row ${index + 1}: Extention=${row.ext || ''}, Password=${row.password || ''}, Mac Address=${row.mac || ''}`)
        .join('\n');
    }

    function validateExcelRow(row) {
      const missing = [];
      if (!row.ext) missing.push('Extention');
      if (!getPasswordForRow(row)) missing.push('Password');
      if (!row.mac) missing.push('Mac Address');
      return missing;
    }

    async function loadExcelRows(file) {
      const arrayBuffer = await file.arrayBuffer();
      const workbook = XLSX.read(arrayBuffer, { type: 'array' });
      const firstSheetName = workbook.SheetNames[0];

      if (!firstSheetName) {
        throw new Error('The Excel file is empty.');
      }

      const firstSheet = workbook.Sheets[firstSheetName];
      const rawRows = XLSX.utils.sheet_to_json(firstSheet, { defval: '' });

      if (!rawRows.length) {
        throw new Error('No rows were found in the Excel sheet.');
      }

      return rawRows.map(normalizeRow);
    }

    function downloadExcelRows() {
      if (!excelRows.length) {
        setExcelStatus('Please upload an Excel file first.', 'error');
        return;
      }

      if (!(excelPasswordPrefixEl.value || '').trim()) {
        setExcelStatus('Please enter a password prefix first.', 'error');
        return;
      }

      if (typeof JSZip === 'undefined') {
        setExcelStatus('ZIP support is not available right now.', 'error');
        return;
      }

      const zip = new JSZip();
      let validCount = 0;
      const skipped = [];

      excelRows.forEach((row, index) => {
        const missing = validateExcelRow(row);
        if (missing.length) {
          skipped.push(`Row ${index + 1}: missing ${missing.join(', ')}`);
          return;
        }

        zip.file(safeFilenameFromMac(row.mac), buildTextFromRow(row));
        validCount += 1;
      });

      if (!validCount) {
        setExcelStatus(`No valid rows were found. ${skipped.join('; ')}`, 'error');
        return;
      }

      zip.generateAsync({ type: 'blob' })
        .then((blob) => {
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = 'generated_txt_files.zip';
          document.body.appendChild(a);
          a.click();
          a.remove();
          URL.revokeObjectURL(url);

          if (skipped.length) {
            setExcelStatus(`Created ZIP with ${validCount} valid files. Skipped ${skipped.length} invalid row(s): ${skipped.join('; ')}`, 'error');
          } else {
            setExcelStatus(`Created ZIP with ${validCount} files.`, 'ok');
          }
        })
        .catch((error) => {
          console.error(error);
          setExcelStatus('Could not create the ZIP file.', 'error');
        });
    }

    function switchTab(nextTab) {
      tabs.forEach((tab) => {
        const isActive = tab.dataset.tab === nextTab;
        tab.classList.toggle('active', isActive);
      });

      panels.forEach((panel) => {
        const isActive = panel.dataset.panel === nextTab;
        panel.classList.toggle('active', isActive);
      });
    }

    document.getElementById('genPasswordBtn').addEventListener('click', () => {
      passwordEl.value = generatePassword(20);
      updatePreview();
      setStatus('Password generated.', 'ok');
    });

    document.getElementById('downloadBtn').addEventListener('click', downloadTxt);

    document.getElementById('clearBtn').addEventListener('click', () => {
      [nameEl, macEl, datetimeEl, extEl, passwordEl].forEach((el) => {
        el.value = '';
      });
      excelFileEl.value = '';
      excelRows = [];
      renderExcelPreview();
      previewEl.textContent = 'Your generated text will appear here.';
      setStatus('Cleared.', 'ok');
      setExcelStatus('Cleared.', 'ok');
    });

    downloadExcelBtn.addEventListener('click', downloadExcelRows);

    excelFileEl.addEventListener('change', async (event) => {
      const [file] = event.target.files;

      if (!file) {
        excelRows = [];
        renderExcelPreview();
        setExcelStatus('No file selected.', 'error');
        return;
      }

      try {
        excelRows = await loadExcelRows(file);
        renderExcelPreview();
        setExcelStatus(`Loaded ${excelRows.length} rows from ${file.name}.`, 'ok');
      } catch (error) {
        excelRows = [];
        renderExcelPreview();
        setExcelStatus(error.message || 'Could not read the Excel file.', 'error');
      }
    });

    tabs.forEach((tab) => {
      tab.addEventListener('click', () => switchTab(tab.dataset.tab));
    });

    const now = new Date();
    now.setMinutes(now.getMinutes() - now.getTimezoneOffset());
    datetimeEl.value = now.toISOString().slice(0, 16);
    passwordEl.value = generatePassword(20);
    updatePreview();
    renderExcelPreview();
    setExcelStatus('Upload an Excel file to generate TXT files.', 'ok');
 