
    const nameEl = document.getElementById('name');
    const macEl = document.getElementById('mac');
    const datetimeEl = document.getElementById('datetime');
    const extEl = document.getElementById('ext');
    const passwordEl = document.getElementById('password');
    const previewEl = document.getElementById('preview');
    const statusEl = document.getElementById('status');

    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';

    function generatePassword(length = 20) {
      const values = new Uint32Array(length);
      crypto.getRandomValues(values);
      let out = '';
      for (let i = 0; i < length; i++) {
        out += chars[values[i] % chars.length];
      }
      return out;
    }

    function formatDateTime(value) {
      if (!value) return '';
      const d = new Date(value);
      if (Number.isNaN(d.getTime())) return value;
      return d.toLocaleString('en-US', {
        year: 'numeric',
        month: 'numeric',
        day: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
        second: '2-digit'
      });
    }

    function buildText() {
      const name = nameEl.value.trim();
      const dt = formatDateTime(datetimeEl.value);
      const ext = extEl.value.trim();
      const password = passwordEl.value.trim() || generatePassword(20);

      return [
        `## AUTOGENERATED by ${name} Avaya Auto Login Enabler at ${dt}`,
        `SET FORCE_SIP_USERNAME "${ext}"`,
        `SET FORCE_SIP_PASSWORD "${password}"`
      ].join('\n');
    }

    function setStatus(message, type = '') {
      statusEl.textContent = message;
      statusEl.className = `status ${type}`.trim();
    }

    function updatePreview() {
      previewEl.textContent = buildText();
    }

    function validateFields() {
      const missing = [];
      if (!nameEl.value.trim()) missing.push('Name');
      if (!macEl.value.trim()) missing.push('MAC Address');
      if (!datetimeEl.value.trim()) missing.push('Date & Time');
      if (!extEl.value.trim()) missing.push('Ext Number');
      return missing;
    }

    function safeFilenameFromMac() {
      const mac = macEl.value.trim().replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
      return `${mac || 'intake'}_physical.txt`;
    }

    function downloadTxt() {
      const missing = validateFields();
      if (missing.length) {
        setStatus(`Please fill in: ${missing.join(', ')}`, 'error');
        return;
      }

      if (!passwordEl.value.trim()) passwordEl.value = generatePassword(20);

      const blob = new Blob([buildText()], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = safeFilenameFromMac();
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);

      setStatus(`Downloaded ${a.download}`, 'ok');
      updatePreview();
    }

    document.getElementById('genPasswordBtn').addEventListener('click', () => {
      passwordEl.value = generatePassword(20);
      updatePreview();
      setStatus('Password generated.', 'ok');
    });

    // document.getElementById('previewBtn').addEventListener('click', () => {
    //   if (!passwordEl.value.trim()) passwordEl.value = generatePassword(20);
    //   updatePreview();
    //   setStatus('Preview updated.', 'ok');
    // });

    document.getElementById('downloadBtn').addEventListener('click', downloadTxt);

    document.getElementById('clearBtn').addEventListener('click', () => {
      [nameEl, macEl, datetimeEl, extEl, passwordEl].forEach(el => el.value = '');
      previewEl.textContent = 'Your generated text will appear here.';
      setStatus('Cleared.', 'ok');
    });

    // [nameEl, macEl, datetimeEl, extEl].forEach(el => {
    //   el.addEventListener('input', updatePreview);
    // });

    const now = new Date();
    now.setMinutes(now.getMinutes() - now.getTimezoneOffset());
    datetimeEl.value = now.toISOString().slice(0, 16);
    passwordEl.value = generatePassword(20);
    updatePreview();
 